---
abstract: 'Creates bridge between Data::Serializer and Sereal'
author:
  - 'James Rouzier <rouzier@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.9, CPAN::Meta::Converter version 2.140640'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Data-Serializer-Sereal
no_index:
  directory:
    - t
    - inc
requires:
  Test::More: '0'
version: '1.00'
